### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by SoujanyaPonnapalli** [RainBlock/verifier#1]
```
src/blockGenerator.ts:5:60 - error TS2307: Cannot find module './ethereumAccount'.
5 import { EthereumAccount, EthereumAccountFromBuffer } from './ethereumAccount';
```

blockGenerator.ts imports `EthereumAccount`, `EthereumAccountFromBuffer` from ./ethereumAccount on line #5, when there is no file named `ethereumAccount.ts` in the src directory

**Comment by no2chem** [comment]
Sorry about that, forgot to commit. 
Will add CI in a bit so it doesn't happen again.
