### ISSUE TITLE
verifierService: Needs to check if txBinary is valid

### ISSUE THREAD

**Issue by SoujanyaPonnapalli** [RainBlock/verifier#4]
verifierService.ts:21 retrieves the binary transaction from the client request. But if the transaction is undefined, the txBinary on line 21 could be a empty buffer.

On the following line, the txBinary is RlpDecoded, which throws an error if txBinary is an empty buffer.

**Comment by no2chem** [comment]
I guess I can throw an error to the client, but I don't understand why this is a problem?

**Comment by SoujanyaPonnapalli** [comment]
While testing e2e, I see that the verifier receives an empty transaction and throws an uncaught exception. But, I could not reliably reproduce this behavior. If I can reproduce it I will open an issue on the client. If it is just random, then having a check at the verifier helps.

Let me update you on this issue.

**Comment by SoujanyaPonnapalli** [comment]
Closed by [c2a7137](https://github.com/RainBlock/verifier/commit/c2a7137d1fe0025ad5b1ca7f87bee12be295aad0)
